[package]
name = "faer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.18.0"
generativity = "1.1.0"
num-complex = { version = "0.4.6", features = ["rand"] }
reborrow = "0.5.5"

rayon = { version = "1.10.0", optional = true }
log = { version = "0.4.22", optional = true }

dyn-stack = { path = "../../dynstack" }
pulp = { path = "../../pulp/pulp" }
equator = { path = "../../equator/equator" }

gemm = { version = "0.18.0", default-features = false }
rand = "0.8.5"

faer-traits = { path = "../faer-traits" }
faer-macros = { path = "../faer-macros" }
rand_distr = "0.4.3"
libm = "0.2.8"
num-traits = "0.2.19"
azucar = { path = "../../azucar/azucar" }

[features]
default = ["std", "rayon"]
std = [
  "gemm/std",
  "pulp/std",
]
nightly = [
  "pulp/nightly",
  "gemm/nightly",
]
rayon = ["dep:rayon", "gemm/rayon"]
perf-warn = ["log"]

[dev-dependencies]
assert_approx_eq = "1.1.0"
diol = { version = "0.8.3", default-features = false }

[[bench]]
name = "bench"
harness = false
