[package]
name = "faer"
version = "0.21.0"
edition = "2021"

[dependencies]
bytemuck = "1.18.0"
generativity = "1.1.0"
num-complex = { version = "0.4.6", features = ["rand"] }
reborrow = "0.5.5"

rayon = { version = "1.10.0", optional = true }
log = { version = "0.4.22", optional = true }

dyn-stack = { path = "../../dynstack" }
pulp = { path = "../../pulp/pulp" }
equator = { path = "../../equator/equator" }
azucar = { path = "../../azucar/azucar" }

gemm = { path = "../../gemm/gemm", default-features = false }
rand = "0.8.5"

faer-traits = { path = "../faer-traits" }
faer-macros = { path = "../faer-macros" }
rand_distr = "0.4.3"
libm = "0.2.8"
num-traits = "0.2.19"
npyz = "0.8.3"
serde = "1.0.217"

[features]
default = [
  "std",
  "rayon",
  "sparse-linalg",
]
std = [
  "gemm/std",
  "pulp/std",
]
nightly = [
  "pulp/nightly",
  "pulp/nightly-x86-v4",
  "gemm/nightly",
]
rayon = ["dep:rayon", "gemm/rayon"]
perf-warn = ["log"]

linalg = []
sparse = []
sparse-linalg = ["sparse", "linalg"]

[dev-dependencies]
amd = "0.2.2"
assert_approx_eq = "1.1.0"
diol = { version = "0.8.3", default-features = false }
matrix-market-rs = "0.1.3"
serde = "1.0.217"
serde_test = "1.0.177"

[[bench]]
name = "bench"
harness = false
